package frc.robot.utils;

import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import frc.robot.subsystems.Superstructure;

//--------------------------------------------------------------------------//
//                 DO NOT EDIT THIS FILE UNLESS YOU ARE LEX                 //
//--------------------------------------------------------------------------//

public class StateRequest {
    private static Superstructure superstructure;
    private static final StateRequestHandler handler = new StateRequestHandler();

    public static void init(Superstructure superstructure) {
        StateRequest.superstructure = superstructure;
    }

    @SafeVarargs
    public static <T extends Enum<T>> void addOneWayExclusion(T fromState, T... excludedStates) {
        if (superstructure == null) {
            throw new RuntimeException("StateRequest not initialized. Call StateRequest.init() first");
        }

        StateHandler<?> handlerA = superstructure.handlers.get(fromState.getClass());

        if (handlerA != null) {
            @SuppressWarnings("unchecked")
            StateHandler<T> typedHandlerA = (StateHandler<T>) handlerA;
            for (T excludedState : excludedStates) {
                typedHandlerA.addOneWayExclusion(fromState, excludedState);
            }
        }
    }

    @SafeVarargs
    public static <T extends Enum<T>> void addTwoWayExclusion(T fromState, T... otherStates) {
        if (superstructure == null) {
            throw new RuntimeException("StateRequest not initialized. Call StateRequest.init() first");
        }

        for (T otherState : otherStates) {
            StateHandler<?> handlerA = superstructure.handlers.get(fromState.getClass());
            StateHandler<?> handlerB = superstructure.handlers.get(otherState.getClass());

            if (handlerA != null && handlerB != null) {
                @SuppressWarnings("unchecked")
                StateHandler<T> typedHandlerA = (StateHandler<T>) handlerA;
                @SuppressWarnings("unchecked")
                StateHandler<T> typedHandlerB = (StateHandler<T>) handlerB;

                typedHandlerA.addOneWayExclusion(fromState, otherState);
                typedHandlerB.addOneWayExclusion(otherState, fromState);
            }
        }
    }

    private static class StateRequestHandler implements InvocationHandler {
        @Override
        public Object invoke(Object proxy, Method method, Object[] args) {
            if (superstructure == null) {
                throw new RuntimeException("StateRequest not initialized. Call StateRequest.init() first");
            }

            updateStateWithType(args[0]);
            return proxy;
        }

        @SuppressWarnings("unchecked")
        private <T extends Enum<T>> void updateStateWithType(Object stateObj) {
            if (stateObj instanceof Enum<?> enumValue) {
                if (enumValue.getDeclaringClass().isEnum()) {
                    T state = (T) enumValue;

                    Class<?> rawType = enumValue.getClass();
                    if (rawType instanceof Class<?>) {
                        Class<T> stateType = (Class<T>) rawType;

                        Object handlerObj = superstructure.handlers.get(stateType);
                        if (handlerObj instanceof StateHandler<?>) {
                            StateHandler<T> handler = (StateHandler<T>) handlerObj;
                            handler.getSubsystemStates().updateState(state);
                        }
                    }
                }
            }
        }
    }

    public static <T extends Enum<T>> IStateRequest create(T state) {
        IStateRequest request = (IStateRequest) Proxy.newProxyInstance(
                StateRequest.class.getClassLoader(),
                new Class<?>[] { IStateRequest.class },
                handler);
        handler.updateStateWithType(state);
        return request;
    }

}